version: '3.8'
services:

  diploma-site:

    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082" # Map container port 8082 to localhost 8082
    environment:
      # Server & Database
      SERVER_PORT: 8082
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/diploma?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

      # Keycloak Configuration
      KEYCLOAK_AUTH_SERVER_URL: http://keycloak:8080
      KEYCLOAK_REALM: diploma-application-realm
      KEYCLOAK_RESOURCE: diploma-application
      KEYCLOAK_CREDENTIALS_SECRET: T1mvBiSZrf48XcpUYiRkqgCgXCjK1odv
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://keycloak:8080/realms/diploma-application-realm

      # OAuth2 Client Registration
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_ID: diploma-application
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_SECRET: T1mvBiSZrf48XcpUYiRkqgCgXCjK1odv
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_SCOPE: openid,profile
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_AUTHORIZATION_GRANT_TYPE: authorization_code
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_REDIRECT_URI: "{baseUrl}/login/oauth2/code/{registrationId}"
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI: http://keycloak:8080/realms/diploma-application-realm

      # Logging
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: DEBUG
      LOGGING_LEVEL_ORG_KEYCLOAK: DEBUG
    restart: always


volumes:
  mysql_data:

